# This is the base docker compose file used in both dev and prod
rabbitmq:
  image: rabbitmq

celery:
  user: inspector
  build: ./
  working_dir: /opt/inspector
  command: celery -A IonInspector.celeryconfig worker -l info
  links:
    - rabbitmq
    - postgres

django:
  user: inspector
  build: ./
  working_dir: /opt/inspector
  command: bash -c "sleep 5 && ./manage.py syncdb --noinput && ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:8080"
  links:
    - postgres
    - celery
    - rabbitmq

postgres:
  image: postgres:9.3
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=IonInspector
    - PG_HOME=/var/lib/postgresql