# This is the base docker compose file used in both dev and prod
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.16-management

  celery:
    user: inspector
    working_dir: /opt/inspector
    command: python -m celery -A IonInspector.celeryconfig worker -l info
    links:
      - rabbitmq
      - postgres

  django:
    user: inspector
    working_dir: /opt/inspector
    command: bash -c "python -u wait_for_postgres.py && python ./manage.py migrate --noinput && python ./manage.py runserver 0.0.0.0:8000"
    links:
      - postgres
      - celery
      - rabbitmq

  nginx:
    environment:
      - NGINX_HTTP_PORT_NUMBER=8080
    links:
      - django

  postgres:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=IonInspector
      - PG_HOME=/var/lib/postgresql
