# This file is used in prod only and has to be mauanlly merged when running docker-compose
celery:
  volumes:
    - /var/lib/inspector/celery:/var/log/celery
    - /var/lib/inspector/media:/var/lib/inspector/media

django:
  volumes:
    - /var/lib/inspector/media:/var/lib/inspector/media
  ports:
    - "8657:8080"

postgres:
  volumes:
    - /var/lib/inspector/postgres/postgresql_data:/var/lib/postgresql/data
    - /var/lib/inspector/postgres/postgresql_log:/var/log/postgresql