# This file is used in prod only and has to be mauanlly merged when running docker-compose
rabbitmq:
  user: $UID

celery:
  user: $UID
  volumes:
    - /var/lib/inspector/celery:/var/log/celery

django:
  user: $UID
  volumes:
    - /var/lib/inspector/media:/var/lib/inspector/media
  ports:
    - "8657:80"

postgres:
  user: $UID
  volumes:
    - /var/lib/inspector/postgres/postgresql_data:/var/lib/postgresql/data
    - /var/lib/inspector/postgres/postgresql_log:/var/log/postgresql