# This is the base docker compose file used in both dev and prod
version: '3'
services:
  rabbitmq:
    image: rabbitmq

  celery:
    user: inspector
    build: ./
    working_dir: /opt/inspector
    command: python -m celery -A IonInspector.celeryconfig worker -l info
    links:
      - rabbitmq
      - postgres

  django:
    user: inspector
    build: ./
    working_dir: /opt/inspector
    command: bash -c "service ssh start && python -u wait_for_postgres.py && ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:8080"
    links:
      - postgres
      - celery
      - rabbitmq

  postgres:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=IonInspector
      - PG_HOME=/var/lib/postgresql