# This file is used in dev only and is automatically merged when running docker-compose
celery:
  volumes:
    - .:/opt/inspector
    - ./.local/celery:/var/log/celery
    - ./.local/media:/var/lib/inspector/media

django:
  volumes:
    - .:/opt/inspector
    - ./.local/media:/var/lib/inspector/media
  ports:
    - "8080:8080"

postgres:
  volumes:
      - ./.local/postgresql_data:/var/lib/postgresql/data
      - ./.local/postgresql_log:/var/log/postgresql
