# This file is used in prod only and has to be mauanlly merged when running docker-compose
celery:
  volumes:
    - /var/lib/inspector/celery:/var/log/celery
    - /mnt/raid/inspector/media:/var/lib/inspector/media
    - /var/log/inspector:/var/log/inspector

django:
  volumes:
    - /var/lib/inspector/media:/var/lib/inspector/media
    - /var/log/inspector:/var/log/inspector
  ports:
    - "8657:8080"

postgres:
  volumes:
    - /var/lib/inspector/postgres/postgresql_data:/var/lib/postgresql/data
    - /var/lib/inspector/postgres/postgresql_log:/var/log/postgresql