# This file is used in dev only and is automatically merged when running docker-compose
version: '3'
services:
  celery:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: vulcan.itw:5000/inspector_celery:latest
    environment:
      - DATABASE_PASSWORD=docker
      - DATABASE_USERNAME=docker
      - DEBUG=True
      - SECRET_KEY="@0gi@=8!#@w!g8d6vibm9+576!rhe949a#w)unk+3s5f4fe0x2"
    volumes:
      - .:/opt/inspector:ro
      - ./.local/logs/celery:/var/log/inspector:delegated
      - inspector-media:/var/lib/inspector/media

  django:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: vulcan.itw:5000/inspector_django:latest
    ports:
      - "8090:8000"
    environment:
      - DATABASE_PASSWORD=docker
      - DATABASE_USERNAME=docker
      - DEBUG=True
      - SECRET_KEY="@0gi@=8!#@w!g8d6vibm9+576!rhe949a#w)unk+3s5f4fe0x2"
    volumes:
      - .:/opt/inspector:ro
      - ./.local/logs/django:/var/log/inspector:delegated
      - inspector-media:/var/lib/inspector/media
      - nginx-temp:/var/lib/inspector/nginxTemp

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    image: vulcan.itw:5000/inspector_uploader:latest
    volumes:
      - .:/opt/inspector:ro
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
      - inspector-media:/var/lib/inspector/media
      - nginx-temp:/var/lib/inspector/nginxTemp
      - nginx-logs:/opt/bitnami/nginx/logs
    ports:
      - "8080:8080"

  postgres:
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - postgresql-log:/var/log/postgresql
    ports:
      - "5433:5432"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq

volumes:
  postgresql-data:
  postgresql-log:
  inspector-media:
  rabbit-data:
  nginx-logs:
  nginx-temp:
