rabbitmq:
  image: rabbitmq

celery:
  build: ./
  volumes:
    - .:/opt/inspector
    - ./celery:/var/log/celery/
  working_dir: /opt/inspector
  #environment:
  #  - C_FORCE_ROOT=true # argh!
  #command: celery worker -A IonInspector.celeryconfig -E -l info --concurrency=3
  command: bash -c "service celeryd start && sleep infinity"
  links:
    - rabbitmq
    - postgres

django:
  build: ./
  working_dir: /opt/inspector
  command: bash -c "sleep 5 && ./manage.py syncdb --noinput && ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:80"
  volumes:
    - .:/opt/inspector
  ports:
    - "8080:80"
  links:
    - postgres
    - celery
    - rabbitmq

postgres:
  image: postgres:9.3
  restart: always
  volumes:
    - ./postgresql_data:/var/lib/postgresql/data
    - ./postgresql_log:/var/log/postgresql
  expose:
    - "5432"
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=IonInspector
    - PG_HOME=/var/lib/postgresql