rabbitmq:
  image: rabbitmq

celery:
  build: ./
  volumes:
    - .:/opt/inspector
  working_dir: /opt/inspector
  environment:
    - C_FORCE_ROOT=true # argh!
  command: celery worker -A IonInspector.inspector_celery -E -l info --concurrency=3
  links:
    - rabbitmq
    - postgres

django:
  build: ./
  working_dir: /opt/inspector
  command: bash -c "sleep 5 && ./manage.py syncdb --noinput && ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:80"
  volumes:
    - .:/opt/inspector
  ports:
    - "80:80"

  links:
    - postgres:postgres
    - celery
    - rabbitmq

data:
  image: postgres:9.3
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  image: postgres:9.3
  restart: always
  volumes_from:
    - data
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=IonInspector