# This is the base docker compose file used in both dev and prod
version: '3'
services:
  openrefine:
    image: tf-sci/inspector-openrefine:3.4.1
    build:
      context: ./openrefine/
      args: 
        - RELEASE=3.4.1
    restart: always
    command: openrefine-3.4.1/refine -i 0.0.0.0 -d /mnt/refine
    environment:
      - REFINE_MEMORY=2048m
      - REFINE_MIN_MEMORY=2048m
    links:
      - postgres
    volumes:
      - refine-data:/mnt/refine
      - /mnt/raid/inspector/media:/var/lib/inspector/media:ro
    ports:
      - "3333:3333"
