# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180418_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='category',
            field=models.CharField(choices=[(b'SEQ', b'SEQUENCING'), (b'PRE', b'SAMPLE_PREP')], default=b'SEQ', max_length=3),
        ),
    ]
