# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 14:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_diagnostic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='search_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None, db_index=True),
        ),
    ]
