# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_archive_search_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='archive',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
