# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-02 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190725_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'ID')),
                ('serial_number', models.CharField(db_column=b'serial_number', max_length=255, unique=True, verbose_name=b'Serial Number')),
                ('instrument_name', models.CharField(db_column=b'instrument_name', max_length=255, null=True, verbose_name=b'Instrument Name')),
                ('site', models.CharField(db_column=b'site', max_length=255, null=True, verbose_name=b'Site Name')),
                ('fas', models.CharField(blank=True, db_column=b'fas_name', max_length=255, null=True, verbose_name=b'Field Application Scientist')),
                ('fbs', models.CharField(blank=True, db_column=b'fbs_name', max_length=255, null=True, verbose_name=b'Field Bioinformatics Scientist')),
                ('fse', models.CharField(blank=True, db_column=b'fse_name', max_length=255, null=True, verbose_name=b'Field Support Engineer')),
            ],
        ),
    ]
