# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_instrument_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='crc32_sum',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='md5_hash',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='sha1_hash',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
