# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-19 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_archive_hashing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[(b'PGM_Run', b'PGM'), (b'Proton', b'PROTON'), (b'Purification', b'Purification'), (b'S5', b'S5'), (b'Valkyrie', b'Genexus'), (b'OT_Log', b'OT'), (b'Ion_Chef', b'CHEF')], max_length=255, null=True),
        ),
    ]
