# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_add_purification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="category",
            field=models.CharField(
                choices=[
                    (b"SEQ", b"SEQUENCING"),
                    (b"PRE", b"SAMPLE_PREP"),
                    (b"LIB", b"LIBRARY_PREP"),
                ],
                default=b"SEQ",
                max_length=3,
            ),
        ),
    ]
