# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_auto_20210926_2036"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="serial_number",
            field=models.CharField(max_length=30, null=False, default=u''),
        ),
        migrations.AddField(
            model_name="archive",
            name="instrumentId",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="archive",
            name="device_name",
            field=models.CharField(max_length=60, unique=False, null=False, default=u"", blank=False, db_index=False),
        ),
        migrations.AddField(
            model_name="archive",
            name="chip_type",
            field=models.CharField(max_length=12, unique=False, null=False, default=u"", blank=False, db_index=False),
        ),
        migrations.AddField(
            model_name="archive",
            name="runId",
            field=models.IntegerField(null=True),
        ),
    ]
