"""Initial revision

Revision ID: 3127fc2a71d4
Revises: None
Create Date: 2013-05-23 15:51:08.322723

"""

# revision identifiers, used by Alembic.
revision = '3127fc2a71d4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
