"""Add archive summary

Revision ID: 46b6a9200fdd
Revises: 3127fc2a71d4
Create Date: 2013-05-23 16:23:34.792433

"""

# revision identifiers, used by Alembic.
revision = '46b6a9200fdd'
down_revision = '3127fc2a71d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('summary', sa.Unicode(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archives', 'summary')
    ### end Alembic commands ###
